# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac9e9bcce4a49cd4e2076c49c2078abb4d55b8dfddc8a57edcbe7601db83d29ed41822e108dd900dc71964f879e36dc1264632427c28c59953405405587d885e

test:
  secret_key_base: cff162011e8b1ccd3c9056ccc08cc9e5b3ca955f20d36d24df7d7aa160b1dee81fab01f21055e24ff75d9e55129f9e62c8d677328ef3577bbb0f38af9a1931e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
